<?xml version="1.0" ?>
<!DOCTYPE quiz [
  <!ELEMENT quiz (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (id?,question?,answer?)+>
  <!ELEMENT id (#PCDATA)>
  <!ELEMENT question (#PCDATA)>
  <!ELEMENT answer (#PCDATA)>
]>
<quiz>
  <DATA_RECORD>
    <id>1</id>
    <question>What country has the second largest population in the world?</question>
    <answer>India</answer>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>2</id>
    <question>In what country would you find the cities Glasgow and Edinburgh?</question>
    <answer>Scotland</answer>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>3</id>
    <question>What country has a maple leaf on their national flag?</question>
    <answer>Canada</answer>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>4</id>
    <question>What country is home to the Great Barrier Reef?</question>
    <answer>Australia</answer>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>5</id>
    <question>Tapas and paella are dishes that originated in what country?</question>
    <answer>Spain</answer>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>6</id>
    <question>What country was the first to land a man on the moon?</question>
    <answer>USA</answer>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>7</id>
    <question>What is the largest country (by size and population) in South America?</question>
    <answer>Brazil</answer>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>8</id>
    <question>In what country is the Yangtze River found?</question>
    <answer>China</answer>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>9</id>
    <question>The kiwi is a flightless bird that lives in what country?</question>
    <answer>New Zealand</answer>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>10</id>
    <question>In what country would you find the islands Santorini and Mykonos?</question>
    <answer>Greece</answer>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>11</id>
    <question>In what country was Nelson Mandela born?</question>
    <answer>South Africa</answer>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>12</id>
    <question>Adidas and Volkswagen are companies from what country?</question>
    <answer>Germany</answer>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>13</id>
    <question>Zurich is the largest city in what country?</question>
    <answer>Switzerland</answer>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>14</id>
    <question>In what country is the Great Pyramid of Giza found?</question>
    <answer>Egypt</answer>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>15</id>
    <question>In what country would you find the cities Lyon and Marseille?</question>
    <answer>France</answer>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>16</id>
    <question>Leonardo da Vinci was born in what country?</question>
    <answer>Italy</answer>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>17</id>
    <question>In terms of land area, what is the largest country in the world?</question>
    <answer>Russia</answer>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>18</id>
    <question>What country was known as Ceylon until 1972?</question>
    <answer>Sri Lanka</answer>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>19</id>
    <question>In what country would you find the cities Ankara and Istanbul?</question>
    <answer>Turkey</answer>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>20</id>
    <question>Mount Fuji is the highest mountain in what country?</question>
    <answer>Japan</answer>
  </DATA_RECORD>
</quiz>
